name: Reservation
modelClass: Buzz\Oksireserv\Models\Reservation
form: $/buzz/oksireserv/models/reservation/fields.yaml
defaultRedirect: buzz/oksireserv/reservations
create:
    redirect: 'buzz/oksireserv/reservations/update/:id'
    redirectClose: buzz/oksireserv/reservations
update:
    redirect: buzz/oksireserv/reservations
    redirectClose: buzz/oksireserv/reservations
preview: {  }
